{% set python_min = '3.9.6' %}
{% set name = "nomad-camels-driver-voltcraft-pps" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_voltcraft_pps-{{ version }}.tar.gz
  sha256: 64c1757ef1a39c0056a7057ae225c95dc83f64029dd82b0a3bbf6c76822ff842

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pyvisa
    - pyvisa-py

test:
  imports:
    - nomad_camels_driver_voltcraft_pps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Driver for communicating with a Voltcraft PPS power supply.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
