{% set python_min = "3.9.6" %}
{% set name = "nomad-camels-driver-voltcraft-pps" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_voltcraft_pps-{{ version }}.tar.gz
  sha256: 55e0e6ce0afe11741cde5a94ebc0591cdb75bf13045dc8fe8ff59bd201c2a755

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pyvisa
    - pyvisa-py

test:
  imports:
    - nomad_camels_driver_voltcraft_pps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Driver for communicating with a Voltcraft PPS power supply.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
